/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthStarsImport } from './routes/_auth/stars'
import { Route as AuthDashboardImport } from './routes/_auth/dashboard'
import { Route as AuthCollectionsImport } from './routes/_auth/collections'

// Create/Update Routes

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthStarsRoute = AuthStarsImport.update({
  id: '/stars',
  path: '/stars',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthDashboardRoute = AuthDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthCollectionsRoute = AuthCollectionsImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AuthRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth/collections': {
      id: '/_auth/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthCollectionsImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/stars': {
      id: '/_auth/stars'
      path: '/stars'
      fullPath: '/stars'
      preLoaderRoute: typeof AuthStarsImport
      parentRoute: typeof AuthRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthCollectionsRoute: typeof AuthCollectionsRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthStarsRoute: typeof AuthStarsRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCollectionsRoute: AuthCollectionsRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthStarsRoute: AuthStarsRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteRouteWithChildren
  '/collections': typeof AuthCollectionsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/stars': typeof AuthStarsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteRouteWithChildren
  '/collections': typeof AuthCollectionsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/stars': typeof AuthStarsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/collections': typeof AuthCollectionsRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/stars': typeof AuthStarsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/collections' | '/dashboard' | '/stars'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/collections' | '/dashboard' | '/stars'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/collections'
    | '/_auth/dashboard'
    | '/_auth/stars'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth/route.tsx",
      "children": [
        "/_auth/collections",
        "/_auth/dashboard",
        "/_auth/stars"
      ]
    },
    "/_auth/collections": {
      "filePath": "_auth/collections.tsx",
      "parent": "/_auth"
    },
    "/_auth/dashboard": {
      "filePath": "_auth/dashboard.tsx",
      "parent": "/_auth"
    },
    "/_auth/stars": {
      "filePath": "_auth/stars.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
