import type { Metadata } from 'next'
import { Gabarito } from 'next/font/google'

import './globals.css'

const gabarito = Gabarito({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  adjustFontFallback: false,
})

export const metadata: Metadata = {
  title: 'Stargazer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={gabarito.className}>{children}</body>
    </html>
  )
}
