// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: crontab.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getCrontab = `-- name: GetCrontab :one
SELECT user_id, stargazers, created_at, updated_at FROM crontab WHERE user_id = $1
`

func (q *Queries) GetCrontab(ctx context.Context, userID uuid.UUID) (Crontab, error) {
	row := q.db.QueryRow(ctx, getCrontab, userID)
	var i Crontab
	err := row.Scan(
		&i.UserID,
		&i.Stargazers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
