// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Crontab struct {
	UserID     uuid.UUID
	Stargazers int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Owner struct {
	ID        int32
	Name      string
	AvatarUrl string
}

type Repository struct {
	ID          int32
	Name        string
	OwnerID     int32
	HtmlUrl     string
	Homepage    *string
	Description *string
	Watchers    int32
	Forks       int32
	OpenIssues  int32
	Language    string
	Archived    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RepositoryTopic struct {
	RepoID  int32
	TopicID int32
}

type Star struct {
	UserID    uuid.UUID
	RepoID    int32
	IsDelete  bool
	CreatedAt time.Time
	SyncedAt  time.Time
	UpdatedAt time.Time
}

type Topic struct {
	ID   int32
	Name string
}

type User struct {
	ID        uuid.UUID
	ClerkID   string
	CreatedAt time.Time
}
