// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: repository.sql

package db

import (
	"context"
	"time"
)

const upsertOwner = `-- name: UpsertOwner :one
INSERT INTO owner (id, name, avatar_url)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    avatar_url = EXCLUDED.avatar_url
RETURNING id, name, avatar_url
`

type UpsertOwnerParams struct {
	ID        int32
	Name      string
	AvatarUrl string
}

func (q *Queries) UpsertOwner(ctx context.Context, arg UpsertOwnerParams) (Owner, error) {
	row := q.db.QueryRow(ctx, upsertOwner, arg.ID, arg.Name, arg.AvatarUrl)
	var i Owner
	err := row.Scan(&i.ID, &i.Name, &i.AvatarUrl)
	return i, err
}

const upsertRepository = `-- name: UpsertRepository :one
INSERT INTO repositories (id, name, owner_id, html_url, homepage, description, watchers, forks, open_issues, language, archived, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    owner_id = EXCLUDED.owner_id,
    html_url = EXCLUDED.html_url,
    homepage = EXCLUDED.homepage,
    description = EXCLUDED.description,
    watchers = EXCLUDED.watchers,
    forks = EXCLUDED.forks,
    open_issues = EXCLUDED.open_issues,
    language = EXCLUDED.language,
    archived = EXCLUDED.archived,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at
RETURNING id, name, owner_id, html_url, homepage, description, watchers, forks, open_issues, language, archived, created_at, updated_at
`

type UpsertRepositoryParams struct {
	ID          int32
	Name        string
	OwnerID     int32
	HtmlUrl     string
	Homepage    *string
	Description *string
	Watchers    int32
	Forks       int32
	OpenIssues  int32
	Language    string
	Archived    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, upsertRepository,
		arg.ID,
		arg.Name,
		arg.OwnerID,
		arg.HtmlUrl,
		arg.Homepage,
		arg.Description,
		arg.Watchers,
		arg.Forks,
		arg.OpenIssues,
		arg.Language,
		arg.Archived,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.HtmlUrl,
		&i.Homepage,
		&i.Description,
		&i.Watchers,
		&i.Forks,
		&i.OpenIssues,
		&i.Language,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepositoryTopics = `-- name: UpsertRepositoryTopics :many
INSERT INTO repository_topics (repo_id, topic_id)
VALUES ($1, $2)
ON CONFLICT (repo_id, topic_id) DO UPDATE
SET repo_id = EXCLUDED.repo_id,
    topic_id = EXCLUDED.topic_id
RETURNING repo_id, topic_id
`

type UpsertRepositoryTopicsParams struct {
	RepoID  int32
	TopicID int32
}

func (q *Queries) UpsertRepositoryTopics(ctx context.Context, arg UpsertRepositoryTopicsParams) ([]RepositoryTopic, error) {
	rows, err := q.db.Query(ctx, upsertRepositoryTopics, arg.RepoID, arg.TopicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepositoryTopic
	for rows.Next() {
		var i RepositoryTopic
		if err := rows.Scan(&i.RepoID, &i.TopicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTopics = `-- name: UpsertTopics :one
INSERT INTO topics (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE
SET name = EXCLUDED.name
RETURNING id, name
`

func (q *Queries) UpsertTopics(ctx context.Context, name string) (Topic, error) {
	row := q.db.QueryRow(ctx, upsertTopics, name)
	var i Topic
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
