// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: search.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getRepositoriesByLanguagesWithPagination = `-- name: GetRepositoriesByLanguagesWithPagination :many
WITH filtered AS (
    SELECT
        r.id, r.name, r.owner_id, r.html_url, r.homepage, r.description, r.watchers, r.forks, r.open_issues, r.language, r.archived, r.created_at, r.updated_at
    FROM
        stars s
    JOIN
        repositories r ON s.repo_id = r.id
    WHERE
        s.user_id = $1
        AND s.is_delete = FALSE
        AND r.language = ANY($2::text[])
)
SELECT
    id, name, owner_id, html_url, homepage, description, watchers, forks, open_issues, language, archived, created_at, updated_at,
    (SELECT COUNT(*) FROM filtered) AS total_count
FROM
    filtered
ORDER BY
    created_at DESC
LIMIT $3
OFFSET $4
`

type GetRepositoriesByLanguagesWithPaginationParams struct {
	UserID  uuid.UUID
	Column2 []string
	Limit   int32
	Offset  int32
}

type GetRepositoriesByLanguagesWithPaginationRow struct {
	ID          int32
	Name        string
	OwnerID     int32
	HtmlUrl     string
	Homepage    *string
	Description *string
	Watchers    int32
	Forks       int32
	OpenIssues  int32
	Language    string
	Archived    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	TotalCount  int64
}

func (q *Queries) GetRepositoriesByLanguagesWithPagination(ctx context.Context, arg GetRepositoriesByLanguagesWithPaginationParams) ([]GetRepositoriesByLanguagesWithPaginationRow, error) {
	rows, err := q.db.Query(ctx, getRepositoriesByLanguagesWithPagination,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRepositoriesByLanguagesWithPaginationRow
	for rows.Next() {
		var i GetRepositoriesByLanguagesWithPaginationRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.HtmlUrl,
			&i.Homepage,
			&i.Description,
			&i.Watchers,
			&i.Forks,
			&i.OpenIssues,
			&i.Language,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStarredLanguageDistributionByUser = `-- name: GetStarredLanguageDistributionByUser :many
SELECT
	r.language,
	COUNT(r.id) AS COUNT
FROM
	stars s
	JOIN repositories r ON s.repo_id = r.id
WHERE
	s.user_id = $1
	AND s.is_delete = FALSE
GROUP BY
	r.language
ORDER BY
	COUNT DESC
`

type GetStarredLanguageDistributionByUserRow struct {
	Language string
	Count    int64
}

func (q *Queries) GetStarredLanguageDistributionByUser(ctx context.Context, userID uuid.UUID) ([]GetStarredLanguageDistributionByUserRow, error) {
	rows, err := q.db.Query(ctx, getStarredLanguageDistributionByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStarredLanguageDistributionByUserRow
	for rows.Next() {
		var i GetStarredLanguageDistributionByUserRow
		if err := rows.Scan(&i.Language, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStarredRepositoriesByUser = `-- name: ListStarredRepositoriesByUser :many
SELECT
    -- Repository details
    r.id,
    r.name,
    r.html_url,
    r.homepage,
    r.description,
    r.watchers,
    r.forks,
    r.open_issues,
    r.language,
    r.archived,
    r.created_at,
    r.updated_at,
    -- Owner details (aliased to avoid potential conflicts)
    o.name AS owner_name,
    o.avatar_url AS owner_avatar_url,
    -- Aggregate topic names into an array and CAST the result
    COALESCE(
        ARRAY_AGG(t.name ORDER BY t.name) FILTER (WHERE t.id IS NOT NULL),
        ARRAY[]::VARCHAR[] -- Keep the empty array part consistent or also cast if needed
    )::TEXT[] AS topics -- <<< CAST the final result to TEXT[]
FROM
    stars s                     -- Start with the stars table
JOIN
    repositories r ON s.repo_id = r.id -- Join to get repository details
JOIN
    owner o ON r.owner_id = o.id       -- Join to get owner details
LEFT JOIN
    repository_topics rt ON r.id = rt.repo_id -- Left join to include repos with no topics
LEFT JOIN
    topics t ON rt.topic_id = t.id           -- Left join to get topic names
WHERE
    s.user_id = '0c28555f-5844-4c9d-9d13-f6d874d4d0c7'              -- Filter by the specific user's ID
AND
    s.is_delete = false         -- Only include active stars
GROUP BY
    r.id,                       -- Group by repository to aggregate topics
    o.id                        -- Include owner ID in group by (as its details are selected)
ORDER BY
    r.updated_at DESC
`

type ListStarredRepositoriesByUserRow struct {
	ID             int32
	Name           string
	HtmlUrl        string
	Homepage       *string
	Description    *string
	Watchers       int32
	Forks          int32
	OpenIssues     int32
	Language       string
	Archived       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	OwnerName      string
	OwnerAvatarUrl string
	Topics         []string
}

func (q *Queries) ListStarredRepositoriesByUser(ctx context.Context) ([]ListStarredRepositoriesByUserRow, error) {
	rows, err := q.db.Query(ctx, listStarredRepositoriesByUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStarredRepositoriesByUserRow
	for rows.Next() {
		var i ListStarredRepositoriesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HtmlUrl,
			&i.Homepage,
			&i.Description,
			&i.Watchers,
			&i.Forks,
			&i.OpenIssues,
			&i.Language,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.OwnerAvatarUrl,
			&i.Topics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
