// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: user.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUserByClerkId = `-- name: GetUserByClerkId :one
SELECT id, clerk_id, created_at FROM users
WHERE clerk_id = $1
LIMIT 1
`

func (q *Queries) GetUserByClerkId(ctx context.Context, clerkID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkId, clerkID)
	var i User
	err := row.Scan(&i.ID, &i.ClerkID, &i.CreatedAt)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (clerk_id)
VALUES ($1)
RETURNING id, clerk_id, created_at
`

func (q *Queries) InsertUser(ctx context.Context, clerkID string) (User, error) {
	row := q.db.QueryRow(ctx, insertUser, clerkID)
	var i User
	err := row.Scan(&i.ID, &i.ClerkID, &i.CreatedAt)
	return i, err
}

const upsertCrontab = `-- name: UpsertCrontab :one
INSERT INTO crontab (user_id, stargazers, created_at, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET stargazers = $2,
    updated_at = $4
RETURNING user_id, stargazers, created_at, updated_at
`

type UpsertCrontabParams struct {
	UserID     uuid.UUID
	Stargazers int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) UpsertCrontab(ctx context.Context, arg UpsertCrontabParams) (Crontab, error) {
	row := q.db.QueryRow(ctx, upsertCrontab,
		arg.UserID,
		arg.Stargazers,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Crontab
	err := row.Scan(
		&i.UserID,
		&i.Stargazers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserStarRepository = `-- name: UpsertUserStarRepository :one
INSERT INTO stars (user_id, repo_id, is_delete, created_at, synced_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, repo_id) DO UPDATE
SET synced_at = $5
RETURNING user_id, repo_id, is_delete, created_at, synced_at, updated_at
`

type UpsertUserStarRepositoryParams struct {
	UserID    uuid.UUID
	RepoID    int32
	IsDelete  bool
	CreatedAt time.Time
	SyncedAt  time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpsertUserStarRepository(ctx context.Context, arg UpsertUserStarRepositoryParams) (Star, error) {
	row := q.db.QueryRow(ctx, upsertUserStarRepository,
		arg.UserID,
		arg.RepoID,
		arg.IsDelete,
		arg.CreatedAt,
		arg.SyncedAt,
		arg.UpdatedAt,
	)
	var i Star
	err := row.Scan(
		&i.UserID,
		&i.RepoID,
		&i.IsDelete,
		&i.CreatedAt,
		&i.SyncedAt,
		&i.UpdatedAt,
	)
	return i, err
}
