DROP TABLE IF EXISTS crontab;
DROP TABLE IF EXISTS stars;
DROP TABLE IF EXISTS repository_topics;
DROP TABLE IF EXISTS topics;
DROP TABLE IF EXISTS repositories;
DROP TABLE IF EXISTS owner;
DROP TABLE IF EXISTS users;

DROP EXTENSION IF EXISTS "uuid-ossp";