name: 'Push Producer Image'

on:
  push:
    branches:
      - main
    paths:
      - kafka/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: '${{ vars.PROJECT_ID }}'

      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker ${{ vars.LOCATION }}-docker.pkg.dev && \
          echo ${{ secrets.SECRETS_ENV }} | base64 -d > kafka/secrets.env

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: kafka
          push: true
          tags: ${{ vars.LOCATION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.PROJECT }}/stargazer-producer:latest
