name: 'Deploy Transformer to Google Cloud Run'

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: '${{ vars.PROJECT_ID }}'

      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker ${{ vars.LOCATION }}-docker.pkg.dev && \
          echo ${{ secrets.SECRETS_ENV }} > transformer/secrets.env

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: transformer
          push: true
          tags: ${{ vars.LOCATION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.PROJECT }}/stargazer-transformer:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: ${{ vars.LOCATION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.PROJECT }}/stargazer-transformer:latest
          service: stargazer-transformer
          region: ${{ vars.LOCATION }}
          platform: managed
          allow-unauthenticated: true
          resources: |
            cpu: 2000m
            memory: 4Gi
