name: 'Deploy Transformer to Google Cloud Run'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: $PROJECT_ID
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: transformer
          push: true
          tags: ${{ format('{0}-docker.pkg.dev/{1}/{2}/stargazer-transformer:latest', $LOCATION, $PROJECT_ID, $PROJECT) }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: ${{ format('{0}-docker.pkg.dev/{1}/{2}/stargazer-transformer:latest', $LOCATION, $PROJECT_ID, $PROJECT) }}
          service: stargazer-transformer
          region: $LOCATION
          platform: managed
          allow-unauthenticated: true
