name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
    paths:
      - kafka-service/**

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './kafka-service'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_FOR_GHCR }}

      - name: 'Build Image'
        run: |
          echo ${{ secrets.KAFKA_SERVICE_ENV }} | base64 -d > .env &&
          make build-dev && make push-dev

      # - name: 'Deploy Image on render'
      #   run: |
      #     curl ${{ secrets.DEV_RENDER_URL }}
